import type {
  Achievement,
  Action,
  AlertCase,
  AlertCaseMessage,
  AlertTask,
  AppUser,
  TouchPointRequest,
  Booking,
  Conversation,
  ChatMessage,
  DashboardAlert,
  EmergencyEvent,
  GlobalAlertRule,
  Incident,
  Invite,
  LoginHistoryEntry,
  OnboardingVideo,
  Organisation,
  Rag,
  RagAssignment,
  RagQuestion,
  RagTestResult,
} from "./types";

export const ORG_ID = "org-bright-care";
export const ORG2_ID = "org-larkfield";
export const INTERNAL_ORG_ID = "safeiq-internal";

export const organisations: Organisation[] = [
  {
    id: ORG_ID,
    name: "Bright Care Homes Ltd",
    sector: "Health & Social Care",
    kycVerified: true,
  },
  {
    id: ORG2_ID,
    name: "Larkfield Fostering Agency",
    sector: "Fostering & Adoption",
    kycVerified: true,
  },
];

export const users: AppUser[] = [
  {
    id: "u-admin",
    name: "Morgan Ellis",
    email: "morgan.ellis@brightcare.co.uk",
    role: "organisation",
    orgId: ORG_ID,
    jobTitle: "Operations Director",
    avatarColor: "#4f46e5",
    country: "United Kingdom",
    language: "English",
    twoFactorEnabled: true,
    ipLockEnabled: false,
    allowedContacts: ["u-aisha", "u-tom", "u-priya", "u-daniel"],
    directSignUp: true,
    createdAt: "2026-01-12T09:00:00Z",
  },
  {
    id: "u-aisha",
    name: "Aisha Khan",
    email: "aisha.khan@brightcare.co.uk",
    role: "employee",
    teamRole: "employee",
    orgId: ORG_ID,
    jobTitle: "Senior Care Worker",
    avatarColor: "#0d9488",
    country: "United Kingdom",
    language: "English",
    twoFactorEnabled: true,
    ipLockEnabled: false,
    allowedContacts: ["u-admin", "u-tom"],
    mobile: "+44 7700 900123",
    landline: "+44 161 987 6543",
    createdAt: "2026-02-03T09:00:00Z",
  },
  {
    id: "u-tom",
    name: "Tom Green",
    email: "tom.green@brightcare.co.uk",
    role: "employee",
    teamRole: "employee",
    orgId: ORG_ID,
    jobTitle: "Support Worker",
    avatarColor: "#b45309",
    country: "United Kingdom",
    language: "English",
    twoFactorEnabled: false,
    ipLockEnabled: false,
    allowedContacts: ["u-admin", "u-aisha"],
    createdAt: "2026-03-18T09:00:00Z",
  },
  {
    id: "u-priya",
    name: "Priya Patel",
    email: "priya.patel@brightcare.co.uk",
    role: "employee",
    teamRole: "manager",
    orgId: ORG_ID,
    jobTitle: "Night Care Lead",
    avatarColor: "#be185d",
    country: "United Kingdom",
    language: "English",
    twoFactorEnabled: true,
    ipLockEnabled: true,
    allowedContacts: ["u-admin"],
    isSafeguardingLead: true,
    mobile: "+44 7700 900456",
    landline: "+44 161 987 1122",
    createdAt: "2026-04-02T09:00:00Z",
  },
  {
    id: "u-daniel",
    name: "Daniel Osei",
    email: "daniel.osei@brightcare.co.uk",
    role: "employee",
    teamRole: "administrator",
    orgId: ORG_ID,
    jobTitle: "Domiciliary Care Worker",
    avatarColor: "#2563eb",
    country: "United Kingdom",
    language: "Polish",
    twoFactorEnabled: false,
    ipLockEnabled: false,
    allowedContacts: ["u-admin"],
    createdAt: "2026-05-20T09:00:00Z",
  },
  {
    id: "u-safeiq-internal",
    name: "Jordan Reyes",
    email: "jordan.reyes@safeiq.io",
    role: "internal",
    orgId: INTERNAL_ORG_ID,
    jobTitle: "SafeIQ Platform Support",
    avatarColor: "#0f172a",
    country: "United Kingdom",
    language: "English",
    twoFactorEnabled: true,
    ipLockEnabled: false,
    allowedContacts: [],
    directSignUp: true,
    createdAt: "2026-01-01T09:00:00Z",
  },
  {
    id: "u-sam",
    name: "Sam Okafor",
    email: "sam.okafor@larkfield.org.uk",
    role: "organisation",
    orgId: ORG2_ID,
    jobTitle: "Registered Manager",
    avatarColor: "#7c3aed",
    country: "United Kingdom",
    language: "English",
    twoFactorEnabled: true,
    ipLockEnabled: false,
    allowedContacts: ["u-ellie"],
    directSignUp: true,
    createdAt: "2026-06-01T09:00:00Z",
  },
  {
    id: "u-ellie",
    name: "Ellie Novak",
    email: "ellie.novak@larkfield.org.uk",
    role: "employee",
    teamRole: "employee",
    orgId: ORG2_ID,
    jobTitle: "Supervising Social Worker",
    avatarColor: "#059669",
    country: "United Kingdom",
    language: "English",
    twoFactorEnabled: false,
    ipLockEnabled: false,
    allowedContacts: ["u-sam"],
    createdAt: "2026-06-10T09:00:00Z",
  },
];

export const invites: Invite[] = [
  {
    id: "inv-1",
    email: "sarah.jones@brightcare.co.uk",
    orgId: ORG_ID,
    status: "pending",
    magicLink: "https://app.safeiq.io/join/mg-7f3a9c",
    sentAt: "2026-07-20T10:15:00Z",
  },
  {
    id: "inv-2",
    email: "liam.walsh@brightcare.co.uk",
    orgId: ORG_ID,
    status: "cancelled",
    magicLink: "https://app.safeiq.io/join/mg-2b8e11",
    sentAt: "2026-07-10T14:00:00Z",
    respondedAt: "2026-07-11T09:00:00Z",
  },
  {
    id: "inv-3",
    email: "daniel.osei@brightcare.co.uk",
    orgId: ORG_ID,
    status: "accepted",
    magicLink: "https://app.safeiq.io/join/mg-9d10aa",
    sentAt: "2026-05-19T08:00:00Z",
    respondedAt: "2026-05-20T09:00:00Z",
  },
];

export const rags: Rag[] = [
  {
    id: "rag-safeguarding",
    orgId: ORG_ID,
    name: "Safeguarding Policy 2026",
    accessPassword: "Guard#2026",
    createdAt: "2026-02-10T09:00:00Z",
    createdBy: "u-admin",
    colorTag: "#4f46e5",
    category: "Safeguarding",
    description: "Approved safeguarding policy, reporting procedure, and lone-working guidance for all care staff.",
    status: "published",
    escalationNote: "Notify the on-call manager immediately and log a safeguarding concern form within 1 hour.",
    documents: [
      {
        id: "doc-1",
        name: "Safeguarding Adults Policy v3.pdf",
        sizeKb: 842,
        addedBy: "Morgan Ellis",
        addedAt: "2026-02-10T09:10:00Z",
        contentType: "Policy",
        description: "Organisation-wide safeguarding adults policy, covering disclosure, reporting, and escalation.",
        appliesTo: "All teams, all locations",
        accessLevel: "everyone",
        effectiveDate: "2026-02-10",
        reviewDate: "2027-02-10",
        owner: "Morgan Ellis",
        approvalStatus: "approved",
        versions: [
          { version: 1, uploadedAt: "2026-02-10T09:10:00Z", uploadedBy: "Morgan Ellis", note: "Initial upload" },
          { version: 2, uploadedAt: "2026-05-01T11:00:00Z", uploadedBy: "Morgan Ellis", note: "Annual review update" },
          { version: 3, uploadedAt: "2026-07-15T13:20:00Z", uploadedBy: "Morgan Ellis", note: "Added reporting flowchart" },
        ],
      },
      {
        id: "doc-2",
        name: "Reporting a Concern - Flowchart.png",
        sizeKb: 210,
        addedBy: "Morgan Ellis",
        addedAt: "2026-07-15T13:22:00Z",
        contentType: "Procedure",
        description: "Step-by-step flowchart for reporting a safeguarding concern.",
        appliesTo: "All teams, all locations",
        accessLevel: "everyone",
        effectiveDate: "2026-07-15",
        reviewDate: "2026-08-10",
        owner: "Morgan Ellis",
        approvalStatus: "approved",
        versions: [{ version: 1, uploadedAt: "2026-07-15T13:22:00Z", uploadedBy: "Morgan Ellis", note: "Initial upload" }],
      },
    ],
    alertKeywords: [
      { id: "ak-1", keyword: "abuse", enabled: true },
      { id: "ak-2", keyword: "neglect", enabled: true },
      { id: "ak-3", keyword: "self-harm", enabled: true },
      { id: "ak-4", keyword: "suicide", enabled: true },
      { id: "ak-5", keyword: "unsafe", enabled: false },
    ],
  },
  {
    id: "rag-healthsafety",
    orgId: ORG_ID,
    name: "Health & Safety Procedures",
    accessPassword: "SafeSteps!9",
    createdAt: "2026-03-01T09:00:00Z",
    createdBy: "u-admin",
    colorTag: "#0d9488",
    category: "Policy",
    description: "Manual handling, equipment safety, and COSHH guidance for on-site and domiciliary staff.",
    status: "published",
    escalationNote: "Raise a maintenance ticket and notify the site manager the same day.",
    documents: [
      {
        id: "doc-3",
        name: "Manual Handling Guidance.pdf",
        sizeKb: 512,
        addedBy: "Morgan Ellis",
        addedAt: "2026-03-01T09:15:00Z",
        contentType: "Guidance",
        description: "Safe manual handling techniques for care staff.",
        appliesTo: "Care staff, all locations",
        accessLevel: "everyone",
        effectiveDate: "2026-03-01",
        reviewDate: "2027-03-01",
        owner: "Morgan Ellis",
        approvalStatus: "approved",
        versions: [{ version: 1, uploadedAt: "2026-03-01T09:15:00Z", uploadedBy: "Morgan Ellis", note: "Initial upload" }],
      },
      {
        id: "doc-4",
        name: "COSHH Register.xlsx",
        sizeKb: 96,
        addedBy: "Morgan Ellis",
        addedAt: "2026-06-02T10:00:00Z",
        contentType: "Regulation",
        description: "Register of hazardous substances and control measures.",
        appliesTo: "Facilities team",
        accessLevel: "managers",
        effectiveDate: "2026-06-02",
        reviewDate: "2026-08-05",
        owner: "Morgan Ellis",
        approvalStatus: "approved",
        versions: [
          { version: 1, uploadedAt: "2026-06-02T10:00:00Z", uploadedBy: "Morgan Ellis", note: "Initial upload" },
          { version: 2, uploadedAt: "2026-07-01T10:00:00Z", uploadedBy: "Morgan Ellis", note: "Added new cleaning products" },
        ],
      },
    ],
    alertKeywords: [
      { id: "ak-6", keyword: "injury", enabled: true },
      { id: "ak-7", keyword: "fault", enabled: true },
      { id: "ak-8", keyword: "broken", enabled: true },
      { id: "ak-9", keyword: "fire", enabled: false },
    ],
  },
  {
    id: "rag-careplans",
    orgId: ORG_ID,
    name: "Client Care Plans - Ward A",
    accessPassword: "WardA-Care1",
    createdAt: "2026-04-10T09:00:00Z",
    createdBy: "u-admin",
    colorTag: "#be185d",
    category: "Home visits",
    description: "Individual care plan templates and guidance for Ward A residents.",
    status: "published",
    escalationNote: "Notify the family liaison lead before responding to any family query.",
    documents: [
      {
        id: "doc-5",
        name: "Care Plan Template.docx",
        sizeKb: 64,
        addedBy: "Morgan Ellis",
        addedAt: "2026-04-10T09:20:00Z",
        contentType: "Template",
        description: "Standard care plan template for new residents.",
        appliesTo: "Ward A",
        accessLevel: "everyone",
        effectiveDate: "2026-04-10",
        reviewDate: "2027-04-10",
        owner: "Morgan Ellis",
        approvalStatus: "approved",
        versions: [{ version: 1, uploadedAt: "2026-04-10T09:20:00Z", uploadedBy: "Morgan Ellis", note: "Initial upload" }],
      },
    ],
    alertKeywords: [
      { id: "ak-10", keyword: "family", enabled: true },
      { id: "ak-11", keyword: "complaint", enabled: true },
      { id: "ak-12", keyword: "deteriorating", enabled: true },
    ],
  },
];

export const ragAssignments: RagAssignment[] = [
  { userId: "u-aisha", ragId: "rag-safeguarding", accessCode: "AK-4471-SG", assignedAt: "2026-02-11T09:00:00Z", alertOwnerId: "u-priya" },
  { userId: "u-aisha", ragId: "rag-careplans", accessCode: "AK-2290-CP", assignedAt: "2026-04-11T09:00:00Z", alertOwnerId: "u-priya" },
  { userId: "u-tom", ragId: "rag-healthsafety", accessCode: "TG-8834-HS", assignedAt: "2026-03-05T09:00:00Z", alertOwnerId: "u-priya" },
  { userId: "u-priya", ragId: "rag-safeguarding", accessCode: "PP-1123-SG", assignedAt: "2026-04-03T09:00:00Z", alertOwnerId: "u-admin" },
  { userId: "u-priya", ragId: "rag-healthsafety", accessCode: "PP-5567-HS", assignedAt: "2026-04-03T09:00:00Z", alertOwnerId: "u-admin" },
  { userId: "u-daniel", ragId: "rag-careplans", accessCode: "DO-9902-CP", assignedAt: "2026-05-21T09:00:00Z", alertOwnerId: "u-priya" },
];

export const ragQuestions: RagQuestion[] = [
  {
    id: "q-1",
    ragId: "rag-safeguarding",
    userId: "u-aisha",
    text: "What's the first step if a client discloses abuse to me directly?",
    answer:
      "Stay calm, listen without interrupting, reassure them they did the right thing, do not promise confidentiality, and record exactly what was said using their own words. Report to your line manager within 1 hour using the Safeguarding Concern form (see Reporting a Concern flowchart).",
    status: "answered",
    category: "Suspected abuse or neglect",
    askedAt: "2026-07-21T08:30:00Z",
  },
  {
    id: "q-2",
    ragId: "rag-safeguarding",
    userId: "u-priya",
    text: "Client is refusing evening medication again, what do I log?",
    answer:
      "Record time, medication name/dose, reason given by client, and that you offered it again after 15 minutes. Do not force administration. Notify on-call nurse if refusal continues for 2 consecutive doses.",
    status: "answered",
    category: "Client refusing medication",
    askedAt: "2026-07-22T19:10:00Z",
  },
  {
    id: "q-3",
    ragId: "rag-healthsafety",
    userId: "u-tom",
    text: "The hoist in room 4 is making a grinding noise, can I still use it?",
    status: "pending",
    category: "Equipment fault",
    askedAt: "2026-07-23T07:45:00Z",
  },
  {
    id: "q-4",
    ragId: "rag-careplans",
    userId: "u-daniel",
    text: "Mrs. Whitfield's family are asking why her care plan changed without notice, what do I tell them?",
    status: "escalated",
    category: "Family complaint",
    askedAt: "2026-07-23T09:05:00Z",
  },
  {
    id: "q-5",
    ragId: "rag-safeguarding",
    userId: "u-aisha",
    text: "Am I working alone tonight, and what's the lone-working check-in procedure?",
    answer:
      "Lone workers must check in with the on-call coordinator every 2 hours via the AI agent's status button. If a check-in is missed by more than 15 minutes, the coordinator will attempt contact and may dispatch a welfare visit.",
    status: "answered",
    category: "Lone working safety concern",
    askedAt: "2026-07-20T20:00:00Z",
  },
];

export const dashboardAlerts: DashboardAlert[] = [
  {
    id: "al-1",
    orgId: ORG_ID,
    title: "Family complaint escalated",
    detail: "Daniel Osei's question about Mrs. Whitfield's care plan could not be answered by the RAG and needs a response.",
    severity: "high",
    ragId: "rag-careplans",
    userId: "u-daniel",
    createdAt: "2026-07-23T09:05:00Z",
    read: false,
  },
  {
    id: "al-2",
    orgId: ORG_ID,
    title: "Equipment fault reported",
    detail: "Tom Green flagged a grinding noise from the hoist in room 4. Awaiting maintenance triage.",
    severity: "medium",
    ragId: "rag-healthsafety",
    userId: "u-tom",
    createdAt: "2026-07-23T07:45:00Z",
    read: false,
  },
  {
    id: "al-3",
    orgId: ORG_ID,
    title: "Medication refusal logged",
    detail: "Priya Patel logged a second consecutive medication refusal for a client.",
    severity: "medium",
    ragId: "rag-safeguarding",
    userId: "u-priya",
    createdAt: "2026-07-22T19:12:00Z",
    read: true,
  },
  {
    id: "al-4",
    orgId: ORG_ID,
    title: "New device login",
    detail: "Priya Patel logged in from a new device in Manchester, UK.",
    severity: "low",
    userId: "u-priya",
    createdAt: "2026-07-21T22:40:00Z",
    read: true,
  },
];

export const onboardingVideos: OnboardingVideo[] = [
  { id: "v-1", title: "Welcome to SafeIQ", description: "A 2-minute tour of your organisation dashboard and what to set up first.", thumbnailGradient: "from-indigo-500 to-violet-600", audience: "organisation", order: 1, durationSeconds: 128, sprintPosition: 1, category: "Getting Started", userTypes: ["org_admin", "manager"], estimatedMinutes: 2, aiKeywords: ["welcome", "tour", "dashboard"], published: true },
  { id: "v-2", title: "Creating your first RAG", description: "How to create an isolated RAG system, set an access password, and drop in your first documents.", thumbnailGradient: "from-teal-500 to-emerald-600", audience: "organisation", order: 2, durationSeconds: 205, sprintPosition: 2, category: "Getting Started", userTypes: ["org_admin", "manager"], prerequisiteId: "v-1", estimatedMinutes: 4, aiKeywords: ["rag", "create", "documents"], published: true },
  { id: "v-3", title: "Inviting your team", description: "Send magic-link invites, track who's accepted, and assign RAG access codes.", thumbnailGradient: "from-amber-500 to-orange-600", audience: "organisation", order: 3, durationSeconds: 164, sprintPosition: 3, category: "Employees", userTypes: ["org_admin", "manager"], prerequisiteId: "v-2", estimatedMinutes: 3, aiKeywords: ["invite", "team", "employees"], published: true },
  { id: "v-4", title: "Setting up alert categories", description: "Choose which question types should notify your organisation immediately.", thumbnailGradient: "from-rose-500 to-pink-600", audience: "organisation", order: 4, durationSeconds: 142, sprintPosition: 4, category: "Training", userTypes: ["org_admin", "manager"], prerequisiteId: "v-2", estimatedMinutes: 3, aiKeywords: ["alerts", "keywords", "risk"], published: true },
  { id: "v-5", title: "Using the AI agent widget", description: "How the floating AI agent works for you, including switching between assigned RAGs.", thumbnailGradient: "from-sky-500 to-blue-600", audience: "all", order: 5, durationSeconds: 176, sprintPosition: 5, category: "Getting Started", prerequisiteId: "v-1", estimatedMinutes: 3, aiKeywords: ["widget", "ai agent", "ask"], published: true },
  { id: "v-6", title: "Your first day as an employee", description: "What to expect: signing in, accepting your invite, and finding your assigned RAGs.", thumbnailGradient: "from-emerald-500 to-teal-600", audience: "employee", order: 6, durationSeconds: 118, sprintPosition: 1, category: "Getting Started", userTypes: ["employee"], estimatedMinutes: 2, aiKeywords: ["first day", "sign in", "invite"], published: true },
  { id: "v-7", title: "Switching between RAGs", description: "How to use your unique access code to switch the AI agent onto a different RAG.", thumbnailGradient: "from-fuchsia-500 to-purple-600", audience: "employee", order: 7, durationSeconds: 95, sprintPosition: 2, category: "Getting Started", userTypes: ["employee"], prerequisiteId: "v-6", estimatedMinutes: 2, aiKeywords: ["access code", "switch", "rag"], published: true },
  { id: "v-8", title: "Safety features overview", description: "Lock-screen audio recording, the emergency siren, and the Emergency Safe Word - what they do and when to use them.", thumbnailGradient: "from-red-500 to-rose-600", audience: "employee", order: 8, durationSeconds: 210, sprintPosition: 3, category: "Training", userTypes: ["employee"], prerequisiteId: "v-6", estimatedMinutes: 4, aiKeywords: ["safety", "emergency", "siren"], published: true },
  { id: "v-9", title: "Booking time in the calendar", description: "How organisations and employees can book check-ins linked to a specific RAG.", thumbnailGradient: "from-cyan-500 to-teal-600", audience: "all", order: 9, durationSeconds: 88, sprintPosition: 6, category: "General", estimatedMinutes: 2, aiKeywords: ["calendar", "booking", "check-in"], published: true },
];

// Client feedback (17/08/2026, gap-analysis §3): sharing/assignment targeting
// by Team/Department/Location - kept as the lightest possible mock
// representation (static lists) since nothing else in the app needs these as
// real, membership-tracked entities yet.
export const TEAMS = ["Night Care Team", "Domiciliary Team", "Day Services Team"];
export const DEPARTMENTS = ["Care Delivery", "Operations", "People & Culture"];
export const LOCATIONS = ["Leeds - Bright Care House", "Leeds - Riverside Home", "Wakefield - Fieldhead Home"];

export const achievements: Achievement[] = [
  { id: "ach-getting-started", label: "Getting Started", description: "Complete your first Help Hub item.", icon: "✅" },
  { id: "ach-platform-explorer", label: "Platform Explorer", description: "Complete 5 Help Hub items.", icon: "🧭" },
  { id: "ach-org-ready", label: "Organisation Ready", description: "Complete every item in your Help Sprint.", icon: "🔒" },
];

export const bookings: Booking[] = [
  {
    id: "bk-1",
    orgId: ORG_ID,
    title: "Fortnightly supervision",
    withUserId: "u-aisha",
    date: "2026-07-24",
    time: "10:00",
    ragId: "rag-safeguarding",
    accessCode: "AK-4471-SG",
    notes: "Review lone-working check-ins.",
  },
  {
    id: "bk-2",
    orgId: ORG_ID,
    title: "Return-to-work check-in",
    withUserId: "u-tom",
    date: "2026-07-25",
    time: "14:30",
    ragId: "rag-healthsafety",
    accessCode: "TG-8834-HS",
  },
  {
    id: "bk-3",
    orgId: ORG_ID,
    title: "Night shift handover review",
    withUserId: "u-priya",
    date: "2026-07-28",
    time: "09:15",
    ragId: "rag-safeguarding",
    accessCode: "PP-1123-SG",
  },
  {
    id: "bk-4",
    orgId: ORG_ID,
    title: "Touch point - family care plan query",
    withUserId: "u-daniel",
    date: "2026-12-15",
    time: "11:00",
    ragId: "rag-careplans",
    accessCode: "DO-5567-CP",
    notes: "Requested to discuss an open alert.",
    sourceTouchPointRequestId: "tp-1",
  },
];

// Client feedback (18/08/2026, second round): touch-point meeting requests -
// a team member ticks flagged alerts and asks a designated manager
// (RagAssignment.alertOwnerId) to discuss them.
export const touchPointRequests: TouchPointRequest[] = [
  {
    id: "tp-1",
    orgId: ORG_ID,
    requesterId: "u-daniel",
    targetManagerId: "u-priya",
    alertCaseIds: ["case-1"],
    status: "accepted",
    proposedDate: "2026-12-15",
    proposedTime: "11:00",
    resultingBookingId: "bk-4",
    createdAt: "2026-07-23T09:20:00Z",
    respondedAt: "2026-07-23T13:00:00Z",
  },
  {
    id: "tp-2",
    orgId: ORG_ID,
    requesterId: "u-aisha",
    targetManagerId: "u-priya",
    alertCaseIds: ["case-2"],
    status: "pending",
    createdAt: "2026-07-24T08:10:00Z",
  },
];

export const loginHistory: LoginHistoryEntry[] = [
  { id: "lh-1", userId: "u-admin", ip: "81.174.22.9", location: "Leeds, UK", device: "Chrome on Windows", loginAt: "2026-07-23T08:02:00Z", logoutAt: undefined },
  { id: "lh-2", userId: "u-priya", ip: "92.40.11.3", location: "Manchester, UK", device: "Safari on iPhone", loginAt: "2026-07-21T22:40:00Z", logoutAt: "2026-07-22T06:15:00Z" },
  { id: "lh-3", userId: "u-aisha", ip: "81.174.22.44", location: "Leeds, UK", device: "Chrome on Android", loginAt: "2026-07-21T19:58:00Z", logoutAt: "2026-07-22T07:30:00Z" },
  { id: "lh-4", userId: "u-tom", ip: "86.12.90.201", location: "Bradford, UK", device: "Edge on Windows", loginAt: "2026-07-20T07:55:00Z", logoutAt: "2026-07-20T16:10:00Z" },
  { id: "lh-5", userId: "u-admin", ip: "81.174.22.9", location: "Leeds, UK", device: "Chrome on Windows", loginAt: "2026-07-20T08:00:00Z", logoutAt: "2026-07-20T17:45:00Z" },
  { id: "lh-6", userId: "u-sam", ip: "51.9.44.12", location: "Guildford, UK", device: "Chrome on macOS", loginAt: "2026-07-22T08:30:00Z", logoutAt: "2026-07-22T17:00:00Z" },
];

export const conversations: Conversation[] = [
  { id: "conv-admin-aisha", participantIds: ["u-admin", "u-aisha"], label: "Aisha Khan" },
  { id: "conv-admin-tom", participantIds: ["u-admin", "u-tom"], label: "Tom Green", relatedRagId: "rag-healthsafety" },
  { id: "conv-aisha-tom", participantIds: ["u-aisha", "u-tom"], label: "Tom Green" },
  { id: "conv-admin-daniel", participantIds: ["u-admin", "u-daniel"], label: "Daniel Osei", relatedAlertCaseId: "case-1" },
];

export const chatMessages: ChatMessage[] = [
  { id: "m-1", conversationId: "conv-admin-aisha", senderId: "u-aisha", kind: "text", text: "Morning - all quiet on shift, checking in as scheduled.", sentAt: "2026-07-23T06:02:00Z" },
  { id: "m-2", conversationId: "conv-admin-aisha", senderId: "u-admin", kind: "text", text: "Received, thanks Aisha. Ping me if anything changes with Mrs Whitfield.", sentAt: "2026-07-23T06:05:00Z" },
  { id: "m-3", conversationId: "conv-admin-tom", senderId: "u-tom", kind: "text", text: "Flagged the hoist issue in room 4 via the Health & Safety RAG.", sentAt: "2026-07-23T07:46:00Z" },
  { id: "m-4", conversationId: "conv-admin-daniel", senderId: "u-daniel", kind: "text", text: "Mrs. Whitfield's family are asking why her care plan changed without notice, what do I tell them?", sentAt: "2026-07-23T09:05:00Z" },
];

export const alertCases: AlertCase[] = [
  {
    id: "case-1",
    orgId: ORG_ID,
    ragId: "rag-careplans",
    userId: "u-daniel",
    ownerId: "u-priya",
    keyword: "family",
    questionId: "q-4",
    status: "open",
    severity: "high",
    participantIds: [],
    context: "Reporting a concern raised by a resident's family, not describing their own risk.",
    createdAt: "2026-07-23T09:05:00Z",
  },
  {
    id: "case-2",
    orgId: ORG_ID,
    ragId: "rag-safeguarding",
    userId: "u-aisha",
    ownerId: "u-priya",
    keyword: "abuse",
    questionId: "q-1",
    status: "closed",
    severity: "critical",
    participantIds: [],
    context: "Describing their own risk directly.",
    createdAt: "2026-07-21T08:30:00Z",
    closedAt: "2026-07-21T10:15:00Z",
    closedBy: "u-priya",
  },
];

export const actions: Action[] = [
  {
    id: "act-1",
    orgId: ORG_ID,
    ragId: "rag-safeguarding",
    assigneeId: "u-priya",
    title: "Review Aisha Khan's safeguarding alert case",
    priority: "urgent",
    dueAt: "2026-08-18",
    status: "open",
    sourceAlertCaseId: "case-2",
    createdAt: "2026-07-21T08:35:00Z",
  },
  {
    id: "act-2",
    orgId: ORG_ID,
    ragId: "rag-careplans",
    assigneeId: "u-priya",
    title: "Follow up with Daniel Osei's family query",
    priority: "high",
    dueAt: "2026-08-19",
    status: "in_progress",
    sourceAlertCaseId: "case-1",
    createdAt: "2026-07-23T09:10:00Z",
  },
  {
    id: "act-3",
    orgId: ORG_ID,
    ragId: "rag-healthsafety",
    assigneeId: "u-tom",
    title: "Confirm hoist repair completed in room 4",
    priority: "medium",
    dueAt: "2026-08-22",
    status: "open",
    createdAt: "2026-07-23T07:50:00Z",
  },
  {
    id: "act-4",
    orgId: ORG_ID,
    assigneeId: "u-admin",
    title: "Sign off Q3 safeguarding training refresh",
    priority: "low",
    dueAt: "2026-09-01",
    status: "completed",
    createdAt: "2026-07-10T10:00:00Z",
  },
];

export const globalAlertRules: GlobalAlertRule[] = [
  {
    id: "gar-1",
    orgId: ORG_ID,
    phrase: "suicide",
    category: "Self-harm & suicide risk",
    severity: "critical",
    ragScope: "all",
    recipientRoles: ["administrator", "manager"],
    autoCreateAction: true,
    acknowledgementRequired: true,
    status: "active",
    triggeredCount: 3,
    createdBy: "Morgan Ellis",
    createdAt: "2026-06-02T09:00:00Z",
    changeLog: [{ changedBy: "Morgan Ellis", changedAt: "2026-06-02T09:00:00Z", summary: "Rule created (organisation-wide, critical)" }],
  },
  {
    id: "gar-2",
    orgId: ORG_ID,
    phrase: "safeguarding concern",
    category: "Safeguarding",
    severity: "high",
    ragScope: "all",
    recipientRoles: ["administrator", "manager", "support"],
    autoCreateAction: true,
    acknowledgementRequired: false,
    status: "active",
    triggeredCount: 1,
    createdBy: "Morgan Ellis",
    createdAt: "2026-06-10T11:20:00Z",
    changeLog: [{ changedBy: "Morgan Ellis", changedAt: "2026-06-10T11:20:00Z", summary: "Rule created (organisation-wide, high)" }],
  },
  {
    id: "gar-3",
    orgId: ORG_ID,
    phrase: "unsafe staffing levels",
    category: "Operational risk",
    severity: "medium",
    ragScope: "all",
    recipientRoles: ["administrator"],
    autoCreateAction: false,
    acknowledgementRequired: false,
    status: "suggested",
    triggeredCount: 0,
    proposedBy: "Priya Patel",
    proposedAt: "2026-08-10T14:00:00Z",
  },
];

export const alertCaseMessages: AlertCaseMessage[] = [
  {
    id: "acm-1",
    caseId: "case-1",
    senderId: "u-daniel",
    text: "Mrs. Whitfield's family are asking why her care plan changed without notice, what do I tell them?",
    sentAt: "2026-07-23T09:05:00Z",
  },
  {
    id: "acm-2",
    caseId: "case-1",
    senderId: "u-priya",
    text: "I'll call the family this afternoon and update you - don't discuss the change details with them until then.",
    sentAt: "2026-07-23T09:20:00Z",
  },
  {
    id: "acm-3",
    caseId: "case-2",
    senderId: "u-aisha",
    text: "Logged the disclosure and submitted the Safeguarding Concern form as advised.",
    sentAt: "2026-07-21T08:45:00Z",
  },
  {
    id: "acm-4",
    caseId: "case-2",
    senderId: "u-priya",
    text: "Reviewed the form, spoke with Aisha directly - handled correctly, no further action needed. Closing this out.",
    sentAt: "2026-07-21T10:15:00Z",
  },
];

export const alertTasks: AlertTask[] = [
  {
    id: "task-1",
    caseId: "case-1",
    assigneeId: "u-daniel",
    text: "Prepare a written summary of the care plan change for the family call.",
    done: false,
    createdAt: "2026-07-23T09:25:00Z",
  },
];

export const incidents: Incident[] = [];

export const ragTestResults: RagTestResult[] = [];

export const emergencyEvents: EmergencyEvent[] = [
  {
    id: "em-1",
    orgId: ORG_ID,
    userId: "u-priya",
    trigger: "safe_word",
    gpsLat: 53.8008,
    gpsLng: -1.5491,
    nominatedContact: "Morgan Ellis",
    status: "satisfied",
    triggeredAt: "2026-07-18T23:10:00Z",
    resolvedAt: "2026-07-18T23:22:00Z",
  },
];
